### ISSUE TITLE
Nothing is showing if you follow the instructions on laravel 10 installation

### ISSUE THREAD

**Issue by rabol** [ycs77/laravel-wizard#44]
If you follow the instructions, nothing will show when you go to /wizard/user it simply redirect to /wizard/user/name and does not show any thing

**Comment by ycs77** [comment]
Hi @rabol, are you seeing a completely blank screen? or throw the `View [layouts.app] not found.` error? I'm seeing this error because I created Laravel 10 and followed the installation steps.

If is see the error, you can add the `resources/views/layouts/app.blade.php` to fix this.

Example: [Laravel UI layouts/app.blade.php](https://github.com/laravel/ui/blob/3.x/src/Auth/bootstrap-stubs/layouts/app.stub)
